# Dependencies
markdown:         rdiscount
highlighter:      pygments

#
encoding:         "utf-8"
# Permalinks
permalink:        pretty

# Setup
favicon:          /public/img/chenDoInG.ico
title:            chenDoInG
tagline:          '想法太多而书读太少'
description:      'Hello,World! Here is my personal weblog about technology and life.'
url:              http://shelldone.com

author:
  name:           'chenDoInG'
  url:            https://github.com/chendoing

paginate:         5

# Custom vars
version:          1.0.0

# duoshuo
comments :
    provider : duoshuo
    duoshuo :
      short_name : chendoing
